/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const lobbyIndexLazyImport = createFileRoute('/(lobby)/')()
const lobbyLoadLazyImport = createFileRoute('/(lobby)/load')()

// Create/Update Routes

const lobbyIndexLazyRoute = lobbyIndexLazyImport
  .update({
    path: '/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(lobby)/index.lazy').then((d) => d.Route))

const lobbyLoadLazyRoute = lobbyLoadLazyImport
  .update({
    path: '/load',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(lobby)/load.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(lobby)/load': {
      preLoaderRoute: typeof lobbyLoadLazyImport
      parentRoute: typeof rootRoute
    }
    '/(lobby)/': {
      preLoaderRoute: typeof lobbyIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  lobbyLoadLazyRoute,
  lobbyIndexLazyRoute,
])

/* prettier-ignore-end */
